dist: trusty
language: node_js
node_js:
- "stable"
before_install:
- npm i -g npm@6.9.0
install:
- npm install
git:
  depth: 3
cache:
  directories:
  - node_modules
script:
- npm run build
- sonar-scanner

addons:
  sonarcloud:
    organization: "croxx219-github" #

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
