language: node_js
cache: npm
node_js:
- "9.9.0"
- "node"
before_install:
- npm i -g npm@6.9.0
install:
- npm install
stages:
- lint
- test
- build
git:
  depth: 3
jobs:
  include:
  - stage: lint
    script:
    # Run linter
    - npm run lint
  - stage: test
    script:
    # Run tests
    - npm run test
  - stage: build
    script:
    # Build all
    - npm run build:docs
    - npm run build:system
    - npm run build:app
