language: node_js
node_js:
- "stable"
before_install:
- npm i -g npm@6.9.0
git:
  depth: 3
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
